camunda:
  admin:
    client_id: admin-cli
    username: admin
    password: admin
  web-modeler:
    client_id: web-modeler
    username: ${CAMUNDA_WEB_MODELER_USERNAME}
    password: ${CAMUNDA_WEB_MODELER_PASSWORD}